services:
  api:
    image: ghcr.io/yaon-c2h8n2/snoopy-api:latest
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - db
      - pdfconverter
    environment:
      - JDBC_DATABASE_URL=jdbc:postgresql://db:5432/postgres
      - JDBC_DATABASE_USERNAME=postgres
      - JDBC_DATABASE_PASSWORD=postgres
      - JWT_SECRET=jwtultragigasecretkey
      - MAIL_HOST=smtp.example.com
      - MAIL_ADDRESS=yaon@example.com
      - MAIL_PORT=587
      - MAIL_USERNAME=example
      - MAIL_PASSWORD=example
      - MAIL_PROTOCOL=smtp

  client:
    image: ghcr.io/yaon-c2h8n2/snoopy-client:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
    depends_on:
      - api
