name: Docker Image Build

on:
  workflow_dispatch:

jobs:
  build-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Building the API Docker image
        run: docker build ./api/ --tag ghcr.io/${{ secrets.DOCKER_USERNAME }}/snoopy-api:latest
      - name: Push the Docker images to the ghcr.io registry
        run: |
          docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.GITHUB_TOKEN }}
          docker push ghcr.io/${{ secrets.DOCKER_USERNAME }}/snoopy-api:latest

  build-client:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Building the client Docker image
      run: docker build ./client/ --tag ghcr.io/${{ secrets.DOCKER_USERNAME }}/snoopy-client:latest
    - name: Push the Docker images to the ghcr.io registry
      run: |
        docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.GITHUB_TOKEN }}
        docker push ghcr.io/${{ secrets.DOCKER_USERNAME }}/snoopy-client:latest